SOLUTION_NAME = VRCSaveTextManager
SOLUTION_FILE = $(SOLUTION_NAME).sln
MAIN_PROJECT_FILE = $(SOLUTION_NAME)\$(SOLUTION_NAME).csproj
PROJECT_OUTPUTS = $(SOLUTION_NAME)\bin $(SOLUTION_NAME)\obj
ARTIFACTS_BASEDIR = Artifacts
ARTIFACTS_SUBDIR_BASENAME = $(SOLUTION_NAME)
ARTIFACTS_BASENAME = $(SOLUTION_NAME)
BUILD_CONFIG = Release
BUILD_PLATFORM = "Any CPU"
TARGET_NET9 = net9.0-windows
SINGLE_SUFFIX = -single
RM = del /F /Q


all: build

build:
	dotnet restore -p:Platform=$(BUILD_PLATFORM) $(SOLUTION_FILE)
	dotnet build -c $(BUILD_CONFIG) -p:Platform=$(BUILD_PLATFORM) $(SOLUTION_FILE)

deploy: deploy-$(TARGET_NET9)

deploy$(SINGLE_SUFFIX): deploy-$(TARGET_NET9)$(SINGLE_SUFFIX)

deploy-$(TARGET_NET9):
	-dotnet publish -r win-x64 -c $(BUILD_CONFIG) \
		-p:TargetFramework=$(TARGET_NET9);PublishAot=false \
		-o $(ARTIFACTS_BASEDIR)\$(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NET9) $(PROJECT_FILE)
	$(RM) $(ARTIFACTS_BASEDIR)\$(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NET9)\*.pdb \
		$(ARTIFACTS_BASEDIR)\$(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NET9)\*.xml \
		$(ARTIFACTS_BASENAME)-$(TARGET_NET9).zip 2>NUL
	cd $(ARTIFACTS_BASEDIR)
	powershell Compress-Archive -Path $(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NET9) -DestinationPath ..\$(ARTIFACTS_BASENAME)-$(TARGET_NET9).zip
	cd $(MAKEDIR)

deploy-$(TARGET_NET9)$(SINGLE_SUFFIX):
	-dotnet publish -r win-x64 -c $(BUILD_CONFIG) --self-contained=true \
		-p:TargetFramework=$(TARGET_NET9);PublishAot=false;PublishSingleFile=true;PublishReadyToRun=true \
		-o $(ARTIFACTS_BASEDIR)\$(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NET9)$(SINGLE_SUFFIX) $(PROJECT_FILE)
	$(RM) $(ARTIFACTS_BASEDIR)\$(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NET9)$(SINGLE_SUFFIX)\*.pdb \
		$(ARTIFACTS_BASEDIR)\$(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NET9)$(SINGLE_SUFFIX)\*.xml \
		$(ARTIFACTS_BASENAME)-$(TARGET_NET9)$(SINGLE_SUFFIX).zip 2>NUL
	cd $(ARTIFACTS_BASEDIR)
	powershell Compress-Archive -Path $(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NET9)$(SINGLE_SUFFIX) -DestinationPath ..\$(ARTIFACTS_BASENAME)-$(TARGET_NET9)$(SINGLE_SUFFIX).zip
	cd $(MAKEDIR)

clean:
	$(RM) $(PROJECT_OUTPUTS)

distclean:
	$(RM) $(PROJECT_OUTPUTS) $(ARTIFACTS_BASEDIR) $(ARTIFACTS_BASENAME)-*.zip 2>NUL
